In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_excel('customer_data.xlsx')
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [9]:
missing_data = data.isnull().sum()
print("Missing data")
missing_data

Missing data

CustomerID                  0
Gender                      0
Age                         0
Income                      0
City                        0
Region                      0
Frequency_of_Purchases      0
Average_Purchase_Amount     0
Customer_Lifespan_Months    0
Purchase_Channel            0
Date_of_Purchase            0
Churn_Status                0
dtype: int64

In [4]:
from sklearn.impute import SimpleImputer

In [6]:
imputer = SimpleImputer(strategy='mean')
imputer.fit(data[['Income']])
data[['Income']] = imputer.transform(data[['Income']])

In [8]:
imputer_2 = SimpleImputer(strategy='most_frequent')
imputer_2.fit(data[['City']])
data[['City']] = imputer_2.transform(data[['City']])

In [10]:
data.dtypes

CustomerID                   object
Gender                       object
Age                           int64
Income                      float64
City                         object
Region                       object
Frequency_of_Purchases        int64
Average_Purchase_Amount     float64
Customer_Lifespan_Months     object
Purchase_Channel             object
Date_of_Purchase             object
Churn_Status                 object
dtype: object

Dealing with inconsistant values

In [16]:
unique_values = data['Customer_Lifespan_Months'].unique()
unique_values

array([3, 4, 1, 2, 5], dtype=object)

In [15]:
data = data[data['Customer_Lifespan_Months'] != 'XXXX']

In [17]:
data['Customer_Lifespan_Months'].unique()

array([3, 4, 1, 2, 5], dtype=object)

Assign Correct data type

In [18]:
data['Customer_Lifespan_Months'] = data['Customer_Lifespan_Months'].astype(int)

In [20]:
data['Date_of_Purchase'] = data['Date_of_Purchase'].astype('datetime64[ns]')

In [21]:
data.dtypes

CustomerID                          object
Gender                              object
Age                                  int64
Income                             float64
City                                object
Region                              object
Frequency_of_Purchases               int64
Average_Purchase_Amount            float64
Customer_Lifespan_Months             int64
Purchase_Channel                    object
Date_of_Purchase            datetime64[ns]
Churn_Status                        object
dtype: object

Duplicates data

In [23]:
duplicates = data.duplicated()
data[duplicates]

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
80,C021,Female,22,41743.0,Los Angeles,Northeast,4,54.599,1,Online,2023-06-08,No

In [24]:
data.drop_duplicates(inplace=True)

In [28]:
duplicates = data.duplicated()
data[duplicates]

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status]
Index: []